return {
    FA_CHECK_CIRCLE = "\u{F058}",
    FA_CIRCLE_O = "\u{F10C}",
    FA_CHECK_SQUARE = "\u{F046}",
    FA_SQUARE_O = "\u{F096}",
    FA_THUMB_TACK = "\u{F08D}",
    FA_QUESTION_CIRCLE = "\u{F059}",
    FA_GLOBE = "\u{F0AC}",
    FA_DATABASE = "\u{F1C0}",
    FA_REFRESH = "\u{F021}",
    FA_BOOK = "\u{F02D}",
    FA_DOWNLOAD = "\u{F019}",
    FA_ELLIPSIS_VERTICAL = "\u{F142}",
    FA_MAGNIFYING_GLASS = "\u{F002}",
    FA_EXCHANGE = "\u{F0EC}",
    FA_ARROW_DOWN = "\u{F063}",
    FA_CLOUD = "\u{F0C2}",
    FA_FOLDER = "\u{F07B}",
    FA_SHARE = "\u{F064}",
    FA_TRASH = "\u{F1F8}",
    UNICODE_STAR = "\u{2605}",
    UNICODE_STAR_OUTLINE = "\u{2606}",
    FA_PAINT_BRUSH = "\u{F1FC}",
    FA_PLUS = "\u{F067}",
}
